import {
  DESIGNER_EVENT,
  DETECTING_EVENT,
  DOCUMENT_EVENT,
  DRAGON_EVENT,
  EDITOR_EVENT,
  NODE_CHILDREN_EVENT,
  NODE_EVENT,
  PROJECT_EVENT,
  SELECTION_EVENT,
} from '..'

export const GLOBAL_EVENT = {
  EDITOR_EVENT,

  DESIGNER_EVENT,
  DRAGON_EVENT,
  DETECTING_EVENT,
  SELECTION_EVENT,

  PROJECT_EVENT,
  DOCUMENT_EVENT,
  NODE_EVENT,
  NODE_CHILDREN_EVENT,
}
